### ISSUE TITLE
How can I pass an instance of QAbstractListModel ?

### ISSUE THREAD

**Issue by AbdelghaniDr** [hahn-kev/QmlGrid#1]
Hi,
I need to pass an instance of __QAbstractListModel__ that contains the collection of my items and I didn't find a way to do that, am I missing something ???

**Comment by hahn-kev** [comment]
You should just be able to assign the abstract list model to the rows property and it'll work, just like you might do with a [`Repeater`](http://doc.qt.io/qt-5/qml-qtquick-repeater.html#model-prop) using the model property. If you can't get it working with my grid try getting something working with the repeater and if you're still having issues show me a simple example of what's wrong.
